/// MedChain - Patient Registry Module
/// 
/// Handles patient registration and lookup on Sui blockchain.
/// Patients are identified by NIK hash + Ibu Kandung hash (no PII on-chain).
/// 
/// Key design decisions:
/// - No PII stored on-chain — only SHA256 hashes
/// - Registry is a shared object (accessible by all hospitals)
/// - Admin capability pattern for privileged operations
/// - Events emitted for all state changes (indexer-friendly)
module medchain::patient_registry {

    // ===== Imports =====
    use sui::table::{Self, Table};
    use sui::clock::{Self, Clock};
    use sui::event;
    use std::string::{Self, String};

    // ===== Error Codes =====
    const E_PATIENT_ALREADY_EXISTS: u64 = 1001;
    const E_PATIENT_NOT_FOUND:      u64 = 1002;
    const E_UNAUTHORIZED:           u64 = 1003;
    const E_INVALID_NIK_HASH:       u64 = 1004;  // must be 32-byte hex (64 chars)
    const E_INVALID_IBU_HASH:       u64 = 1005;
    const E_PATIENT_INACTIVE:       u64 = 1006;

    // ===== Constants =====
    const HASH_LENGTH: u64 = 64;    // hex-encoded SHA256 → 64 chars
    const STATUS_ACTIVE: u8   = 1;
    const STATUS_INACTIVE: u8 = 0;  // soft-delete / archived

    // ===== Core Structs =====

    /// Singleton admin capability.
    /// Created once at package init, transferred to deployer.
    /// Required for privileged ops: deactivate patient, update metadata.
    public struct AdminCap has key, store {
        id: UID,
    }

    /// Shared registry — one per deployment.
    /// Hospitals and backend query this object by its ID.
    public struct PatientRegistry has key {
        id: UID,
        /// patient_id → PatientRecord
        patients: Table<String, PatientRecord>,
        /// nik_hash → patient_id  (for lookup by NIK hash)
        nik_index: Table<String, String>,
        /// combined_hash → patient_id  (NIK_hash + ibu_hash → id)
        combined_index: Table<String, String>,
        total_patients: u64,
        created_at: u64,
    }

    /// On-chain patient record.
    /// All PII is off-chain; only hashes and non-sensitive metadata here.
    public struct PatientRecord has store {
        patient_id: String,         // "PAT-0001"
        nik_hash: String,           // sha256(NIK) — hex string
        ibu_kandung_hash: String,   // sha256(namaIbuKandung) — hex string
        wallet_pubkey: String,      // derived deterministic pubkey (hex)
        patient_name: String,       // non-sensitive display name
        registered_by: address,     // hospital/backend address that registered
        created_at: u64,
        updated_at: u64,
        status: u8,                 // STATUS_ACTIVE | STATUS_INACTIVE
    }

    // ===== Events =====

    public struct PatientRegistered has copy, drop {
        patient_id: String,
        nik_hash: String,
        wallet_pubkey: String,
        registered_by: address,
        timestamp: u64,
    }

    public struct PatientStatusChanged has copy, drop {
        patient_id: String,
        old_status: u8,
        new_status: u8,
        changed_by: address,
        timestamp: u64,
    }

    public struct PatientMetadataUpdated has copy, drop {
        patient_id: String,
        updated_by: address,
        timestamp: u64,
    }

    // ===== Init =====

    /// Called once on package publish.
    /// Creates the shared registry + admin cap for deployer.
    fun init(ctx: &mut TxContext) {
        // Shared registry — accessible by everyone
        let registry = PatientRegistry {
            id: object::new(ctx),
            patients: table::new(ctx),
            nik_index: table::new(ctx),
            combined_index: table::new(ctx),
            total_patients: 0,
            created_at: 0,  // will be set properly when Clock is available
        };
        transfer::share_object(registry);

        // Admin cap → deployer
        let admin_cap = AdminCap {
            id: object::new(ctx),
        };
        transfer::transfer(admin_cap, ctx.sender());
    }

    // ===== Public Entry Functions =====

    /// Register a new patient.
    /// Called by hospital backend after local credential hashing.
    /// 
    /// @param registry     - shared PatientRegistry object
    /// @param patient_id   - unique ID e.g. "PAT-0001" (generated by backend)
    /// @param nik_hash     - sha256(NIK) hex string, 64 chars
    /// @param ibu_kandung_hash - sha256(namaIbuKandung) hex string, 64 chars
    /// @param wallet_pubkey    - deterministic wallet pubkey (hex)
    /// @param patient_name     - display name (non-sensitive)
    /// @param clock            - Sui clock for timestamp
    public fun register_patient(
        registry: &mut PatientRegistry,
        patient_id: String,
        nik_hash: String,
        ibu_kandung_hash: String,
        wallet_pubkey: String,
        patient_name: String,
        clock: &Clock,
        ctx: &mut TxContext,
    ) {
        // --- Validations ---
        assert!(
            string::length(&nik_hash) == HASH_LENGTH,
            E_INVALID_NIK_HASH
        );
        assert!(
            string::length(&ibu_kandung_hash) == HASH_LENGTH,
            E_INVALID_IBU_HASH
        );
        assert!(
            !table::contains(&registry.patients, patient_id),
            E_PATIENT_ALREADY_EXISTS
        );
        assert!(
            !table::contains(&registry.nik_index, nik_hash),
            E_PATIENT_ALREADY_EXISTS
        );

        let now = clock::timestamp_ms(clock);
        let caller = ctx.sender();

        // --- Build combined index key ---
        // combined_key = nik_hash + ":" + ibu_kandung_hash
        let combined_key = build_combined_key(&nik_hash, &ibu_kandung_hash);

        assert!(
            !table::contains(&registry.combined_index, combined_key),
            E_PATIENT_ALREADY_EXISTS
        );

        // --- Store record ---
        let record = PatientRecord {
            patient_id,
            nik_hash,
            ibu_kandung_hash,
            wallet_pubkey,
            patient_name,
            registered_by: caller,
            created_at: now,
            updated_at: now,
            status: STATUS_ACTIVE,
        };

        // Insert into all indexes
        table::add(&mut registry.nik_index, record.nik_hash, record.patient_id);
        table::add(&mut registry.combined_index, combined_key, record.patient_id);
        table::add(&mut registry.patients, record.patient_id, record);

        registry.total_patients = registry.total_patients + 1;

        // --- Emit event ---
        let stored = table::borrow(&registry.patients, patient_id);
        event::emit(PatientRegistered {
            patient_id: stored.patient_id,
            nik_hash: stored.nik_hash,
            wallet_pubkey: stored.wallet_pubkey,
            registered_by: caller,
            timestamp: now,
        });
    }

    /// Deactivate (soft-delete) a patient record.
    /// Requires AdminCap. Record stays on-chain, status = INACTIVE.
    public fun deactivate_patient(
        _cap: &AdminCap,
        registry: &mut PatientRegistry,
        patient_id: String,
        clock: &Clock,
        ctx: &mut TxContext,
    ) {
        assert!(
            table::contains(&registry.patients, patient_id),
            E_PATIENT_NOT_FOUND
        );

        let record = table::borrow_mut(&mut registry.patients, patient_id);
        assert!(record.status == STATUS_ACTIVE, E_PATIENT_INACTIVE);

        let old_status = record.status;
        record.status = STATUS_INACTIVE;
        record.updated_at = clock::timestamp_ms(clock);

        event::emit(PatientStatusChanged {
            patient_id,
            old_status,
            new_status: STATUS_INACTIVE,
            changed_by: ctx.sender(),
            timestamp: record.updated_at,
        });
    }

    /// Reactivate a previously deactivated patient.
    /// Requires AdminCap.
    public fun reactivate_patient(
        _cap: &AdminCap,
        registry: &mut PatientRegistry,
        patient_id: String,
        clock: &Clock,
        ctx: &mut TxContext,
    ) {
        assert!(
            table::contains(&registry.patients, patient_id),
            E_PATIENT_NOT_FOUND
        );

        let record = table::borrow_mut(&mut registry.patients, patient_id);
        assert!(record.status == STATUS_INACTIVE, E_PATIENT_ALREADY_EXISTS);

        let old_status = record.status;
        record.status = STATUS_ACTIVE;
        record.updated_at = clock::timestamp_ms(clock);

        event::emit(PatientStatusChanged {
            patient_id,
            old_status,
            new_status: STATUS_ACTIVE,
            changed_by: ctx.sender(),
            timestamp: record.updated_at,
        });
    }

    /// Update patient display name (non-PII, safe to update).
    /// Only callable by original registrar or admin.
    public fun update_patient_name(
        registry: &mut PatientRegistry,
        patient_id: String,
        new_name: String,
        clock: &Clock,
        ctx: &mut TxContext,
    ) {
        assert!(
            table::contains(&registry.patients, patient_id),
            E_PATIENT_NOT_FOUND
        );

        let caller = ctx.sender();
        let record = table::borrow_mut(&mut registry.patients, patient_id);
        assert!(record.status == STATUS_ACTIVE, E_PATIENT_INACTIVE);

        // Only original registrar can update name without AdminCap
        assert!(record.registered_by == caller, E_UNAUTHORIZED);

        record.patient_name = new_name;
        record.updated_at = clock::timestamp_ms(clock);

        event::emit(PatientMetadataUpdated {
            patient_id,
            updated_by: caller,
            timestamp: record.updated_at,
        });
    }

    // ===== Public View Functions =====
    // These are read-only — used by other modules (Records, EBG) and off-chain.

    /// Check if a patient exists by patient_id.
    public fun patient_exists(registry: &PatientRegistry, patient_id: &String): bool {
        table::contains(&registry.patients, *patient_id)
    }

    /// Check if a NIK hash is already registered.
    public fun nik_hash_exists(registry: &PatientRegistry, nik_hash: &String): bool {
        table::contains(&registry.nik_index, *nik_hash)
    }

    /// Lookup patient_id by NIK hash alone.
    /// Returns patient_id string.
    public fun get_patient_id_by_nik(
        registry: &PatientRegistry,
        nik_hash: &String,
    ): String {
        assert!(
            table::contains(&registry.nik_index, *nik_hash),
            E_PATIENT_NOT_FOUND
        );
        *table::borrow(&registry.nik_index, *nik_hash)
    }

    /// Lookup patient_id by combined hash (NIK + Ibu Kandung).
    /// Used during login — more secure than NIK alone.
    public fun get_patient_id_by_combined(
        registry: &PatientRegistry,
        nik_hash: &String,
        ibu_kandung_hash: &String,
    ): String {
        let combined_key = build_combined_key(nik_hash, ibu_kandung_hash);
        assert!(
            table::contains(&registry.combined_index, combined_key),
            E_PATIENT_NOT_FOUND
        );
        *table::borrow(&registry.combined_index, combined_key)
    }

    /// Verify credentials (NIK hash + Ibu Kandung hash) match a patient_id.
    /// Returns true if match + patient is active.
    /// Used by login endpoint to confirm identity.
    public fun verify_patient_credentials(
        registry: &PatientRegistry,
        patient_id: &String,
        nik_hash: &String,
        ibu_kandung_hash: &String,
    ): bool {
        if (!table::contains(&registry.patients, *patient_id)) {
            return false
        };

        let record = table::borrow(&registry.patients, *patient_id);

        record.nik_hash == *nik_hash
            && record.ibu_kandung_hash == *ibu_kandung_hash
            && record.status == STATUS_ACTIVE
    }

    /// Get patient wallet pubkey by patient_id.
    /// Used by hospital backend to encrypt medical data.
    public fun get_wallet_pubkey(
        registry: &PatientRegistry,
        patient_id: &String,
    ): String {
        assert!(
            table::contains(&registry.patients, *patient_id),
            E_PATIENT_NOT_FOUND
        );
        let record = table::borrow(&registry.patients, *patient_id);
        assert!(record.status == STATUS_ACTIVE, E_PATIENT_INACTIVE);
        record.wallet_pubkey
    }

    /// Get patient NIK hash by patient_id.
    /// Used by Records module to link records to patients.
    public fun get_nik_hash(
        registry: &PatientRegistry,
        patient_id: &String,
    ): String {
        assert!(
            table::contains(&registry.patients, *patient_id),
            E_PATIENT_NOT_FOUND
        );
        table::borrow(&registry.patients, *patient_id).nik_hash
    }

    /// Get patient status.
    public fun get_patient_status(
        registry: &PatientRegistry,
        patient_id: &String,
    ): u8 {
        assert!(
            table::contains(&registry.patients, *patient_id),
            E_PATIENT_NOT_FOUND
        );
        table::borrow(&registry.patients, *patient_id).status
    }

    /// Get total registered patients count.
    public fun total_patients(registry: &PatientRegistry): u64 {
        registry.total_patients
    }

    /// Get full record data (for admin / audit use).
    /// Returns tuple of core fields.
    public fun get_patient_info(
        registry: &PatientRegistry,
        patient_id: &String,
    ): (String, String, String, String, address, u64, u8) {
        assert!(
            table::contains(&registry.patients, *patient_id),
            E_PATIENT_NOT_FOUND
        );
        let r = table::borrow(&registry.patients, *patient_id);
        (
            r.patient_id,
            r.nik_hash,
            r.wallet_pubkey,
            r.patient_name,
            r.registered_by,
            r.created_at,
            r.status,
        )
    }

    // ===== Internal Helpers =====

    /// Build combined lookup key from two hashes.
    /// Format: "{nik_hash}:{ibu_kandung_hash}"
    fun build_combined_key(nik_hash: &String, ibu_kandung_hash: &String): String {
        let mut key = *nik_hash;
        string::append_utf8(&mut key, b":");
        string::append(&mut key, *ibu_kandung_hash);
        key
    }

    // ===== Test-only helpers =====
    #[test_only]
    public fun init_for_testing(ctx: &mut TxContext) {
        init(ctx)
    }

    #[test_only]
    public fun get_status_active(): u8 { STATUS_ACTIVE }

    #[test_only]
    public fun get_status_inactive(): u8 { STATUS_INACTIVE }
}
