[package]
name = "sgt"
version = "0.1.0"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
sgt = "0x831d1156089ec1caeb5ee8f5a3ea309bbed417da778dc9bc800e76c7ebc7488b"